version: '3.3'
services:
  app:
    build: 
      dockerfile: dsp-archiwebf22-hm-hm-at-workflow/containers/ci-cd/Dockerfile
      context: ../
    container_name: app
    working_dir: /app
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - ${PORT_APP}:80 
    restart: always
  mongo:
    image: mongo:4.0-xenial
    restart: always
    container_name: mongo
    hostname: mongo
    ports:
      - ${PORT_MONGO}:27017
