version: '3.3'
services:
  app:
    build: 
      dockerfile: dsp-archiwebf22-hm-hm-at-workflow/containers/ci-cd/Dockerfile
      context: ../
    container_name: app
    working_dir: /app
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - ${PORT_APP}:80 
    restart: always
  mongo:
    image: mongo:4.0-xenial
    restart: always
    container_name: mongo
    hostname: mongo
    ports:
      - ${PORT_MONGO}:27017
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      sonar.jdbc.url: jdbc:postgresql://db:5432/sonar
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
    depends_on:
      - db
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
 node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
    command:
      - "--web.listen-address=:9100"  

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
