version: '3.3'
services:
  app:
    build: containers/ci-cd
    container_name: app
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - ${PORT_APP}:80
      - 3000:3000
    restart: always
  mongo:
    image: mongo:4.0-xenial
    restart: always
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
volumes:
  mongo_data:
  mongo_configdb:
