version: '3.3'
services:
  app:
    build: 
      dockerfile: dsp-archiwebf22-hm-hm-at-workflow/containers/ci-cd/Dockerfile
      context: ../
    container_name: app
    working_dir: /app
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - 80:80 
      - 443:443
      - 3000:3000
      - 3001:3001
    restart: always
  mongo:
    image: mongo:4.0-xenial
    restart: always
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
