version: '3'

<<<<<<< Updated upstream
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`localhost:5000`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.middlewares.grafana-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
=======
    services : 
  grafana :
    image :  grafana/grafana:latest
    container_name :  grafana
    restart :  always
    ports : 
      -  3000:3000
    volumes :
      -  ./grafana:/var/lib/grafana
      -  ./grafana/provisioning:/etc/grafana/provisioning
      -  ./grafana/dashboards:/var/lib/grafana/dashboards
      -  ./grafana/plugins:/var/lib/grafana/plugins
      -  ./grafana/logs:/var/lib/grafana/logs
      -  ./grafana/data:/var/lib/grafana/data
    user : root
    labels : 
      -  "traefik.enable=true"
      -  "traefik.http.routers.grafana.rule=Host(`localhost:6000`)"
      -  "traefik.http.routers.grafana.entrypoints=websecure"
      -  "traefik.http.routers.grafana.tls=true"
      -  "traefik.http.routers.grafana.tls.certresolver=le"
      -  "traefik.http.routers.grafana.service=grafana"
      -  "traefik.http.services.grafana.loadbalancer.server.port=3000"
      
       traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost:6000`)"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$pw1$SOMEHASH"
      - "traefik.http.middlewares.traefik-auth.basicauth.removeheader=true"
      - "traefik.http.middlewares.traefik-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-auth@file,traefik-redirect@file"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    networks:
      - web
>>>>>>> Stashed changes
