http:

  # Création de nos middlewares
  middlewares:
  	 # Lorsqu'il est utilisé, il redirige le client vers le point d'entrée https
    https-redirect:
      redirectScheme:
        scheme: https
	 
	 # Applique certains en-têtes lorsqu'il est utilisé
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true

    # Lorsqu'il est utilisé, applique le middleware default-headers
    secured:
      chain:
        middlewares:
        - default-headers
      - headers:
          sslRedirect: true
      redirectScheme:
        scheme: https

  # Il s'agit d'une redirection globale http -> https. Avec ceci, vous pouvez seulement définir un routeur https pour vos services, ceci redirigera les utilisateurs venant de http vers votre routeur https.
  # Si vous n'en avez pas besoin, supprimez tout ce qui se trouve sous cette ligne
  routers:
    https-redirouter:
      rule: HostRegexp(`{any:.*}`)
      middlewares: [https-redirect]
      service: dummy

  services:
    dummy:
      loadBalancer:
        servers:
          - url: localhost
